linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  gosec:
    excludes:
      - G402
      - G404
  revive:
    rules:
      - name: var-declaration
        disabled: true

linters:
  enable-all: false
